version: "3.9"

services:
  db:
    image: postgres:17.5
    container_name: bemdosado-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bem_dosado_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bem_dosado_db"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    networks:
      - bemdosado-network

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: bemdosado-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - bemdosado-network

  springboot:
    build: .
    container_name: bemdosado-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bem_dosado_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bemdosado-network

networks:
  bemdosado-network:
    driver: bridge
